cargo-features = ["profile-rustflags"]

[workspace]
members = ["core", "bot", "simulator", "tuner", "upi"]
resolver = "2"

[profile.release]
lto = true
codegen-units = 1

[profile.bench]
lto = true
codegen-units = 1
