[package]
name = "nova-tuner"
version = "0.1.0"
edition = "2021"

[dependencies]
bot = { path = "../bot", package = "nova-bot" }
simulator = { path = "../simulator", package = "nova-simulator" }
rand = "0.8.5"
itertools = "0.13.0"
